name: Get Feed

on:
  schedule:
    - cron: '30 4,9 * * *' # 1:30 AM, 6:30 PM KST
  workflow_dispatch:

jobs:
  get-feed:
    runs-on: ubuntu-latest
    env:
      NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
      NOTION_READER_DATABASE_ID: ${{ secrets.NOTION_READER_DATABASE_ID }}
      NOTION_FEEDS_DATABASE_ID: ${{ secrets.NOTION_FEEDS_DATABASE_ID }}
      RUN_FREQUENCY: 86400 # in seconds
    steps:
      - name: Set up Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Update Notion Feed
        run: |
          node dist/index.js
